// scripts/hershey/build.ts — regenerate vendored Hershey fonts from .jhf data
// (public domain — A. V. Hershey, US NBS).
// Usage: npx tsx scripts/hershey/build.ts            (builds all FONTS below)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

const FONTS = [
  { jhf: "futural.jhf", out: "hersheyFutural.ts", exportName: "FUTURAL", label: 'Hershey Simplex ("futural")' },
  { jhf: "cursive.jhf", out: "hersheyCursive.ts", exportName: "CURSIVE", label: 'Hershey Cursive ("cursive")' },
];

const R = "R".charCodeAt(0);

for (const font of FONTS) {
  const jhf = readFileSync(join(here, font.jhf), "utf8");
  const lines = jhf.split("\n").filter((l) => l.trim().length > 0);
  const entries: string[] = [];

  lines.forEach((line, i) => {
    const code = 32 + i;
    const data = line.slice(8);
    const left = data.charCodeAt(0) - R;
    const right = data.charCodeAt(1) - R;
    const strokes: number[][][] = [];
    let cur: number[][] = [];
    for (let k = 2; k + 1 < data.length; k += 2) {
      const pair = data.slice(k, k + 2);
      if (pair === " R") {
        if (cur.length > 0) strokes.push(cur);
        cur = [];
      } else {
        cur.push([data.charCodeAt(k) - R, data.charCodeAt(k + 1) - R]);
      }
    }
    if (cur.length > 0) strokes.push(cur);
    const s = strokes
      .map((st) => `[${st.map(([x, y]) => `[${x},${y}]`).join(",")}]`)
      .join(",");
    entries.push(`  ${code}: { left: ${left}, right: ${right}, strokes: [${s}] },`);
  });

  const out = `// src/generators/${font.out} — GENERATED by scripts/hershey/build.ts. Do not edit.
// ${font.label} single-stroke font, public domain (A. V. Hershey, US NBS).
// Coordinates: y grows DOWN, baseline at y=9, cap height ≈ -12..9 (21 units).

export type HersheyGlyph = {
  left: number;
  right: number;
  strokes: [number, number][][];
};

export const ${font.exportName}: Record<number, HersheyGlyph> = {
${entries.join("\n")}
};
`;

  const target = join(here, "../../src/generators/", font.out);
  writeFileSync(target, out);
  console.log(`wrote ${target} (${lines.length} glyphs)`);
}
